# Generated by Django 3.1.3 on 2020-12-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201212_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
