# Generated by Django 3.1.3 on 2020-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
